// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CsvImporter.Data.Models;

 public class VEHICLESContext : DbContext
{
    public VEHICLESContext(DbContextOptions<VEHICLESContext> options)
        : base(options)
    {
    }

    public VEHICLESContext()
    {
    }

    public virtual DbSet<Vehicle> Vehicles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Vehicle>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__VEHICLES__3214EC272FF739BB");

            entity.ToTable("VEHICLES");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Color)
                .HasMaxLength(30)
                .HasColumnName("COLOR");
            entity.Property(e => e.Make)
                .HasMaxLength(50)
                .HasColumnName("MAKE");
            entity.Property(e => e.Model)
                .HasMaxLength(50)
                .HasColumnName("MODEL");
            entity.Property(e => e.Reg)
                .HasMaxLength(10)
                .HasColumnName("REG");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    public void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {

    }
}
