// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CsvImporter.Data.Models;

public partial class Vehicle
{
    public int Id { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public string Reg { get; set; }

    public string Color { get; set; }
}